package com.mybankms.accounts.service.Impl;

import com.mybankms.accounts.Constants.AccountsConstants;
import com.mybankms.accounts.DTO.AccountsDTO;
import com.mybankms.accounts.DTO.CustomerDTO;
import com.mybankms.accounts.entity.Accounts;
import com.mybankms.accounts.entity.Customer;
import com.mybankms.accounts.exception.CustomerAlreadyExistsException;
import com.mybankms.accounts.exception.ResourceNotFoundException;
import com.mybankms.accounts.mapper.AccountsMapper;
import com.mybankms.accounts.mapper.CustomerMapper;
import com.mybankms.accounts.repository.AccountRepository;
import com.mybankms.accounts.repository.CustomerRepository;
import com.mybankms.accounts.service.IAccountsService;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Optional;
import java.util.Random;

@Service
@AllArgsConstructor
public class AccountsServiceImpl implements IAccountsService {

    private AccountRepository accountRepository;
    private CustomerRepository customerRepository;

    @Override
    public void createAccount(CustomerDTO customerDTO) {
        Customer customer = CustomerMapper.MapToCustomer(customerDTO, new Customer());
        Optional<Customer> optionalCustomer = customerRepository.findByMobileNumber(customerDTO.getMobileNumber());
        if (optionalCustomer.isPresent()) {
            throw new CustomerAlreadyExistsException("Customer already registered with given mobile number." + customerDTO.getMobileNumber());
        }
        Customer savedCustomer = customerRepository.save(customer); // saving in another variable so that the customerID will be generated by JPA
        accountRepository.save(createNewAccount(savedCustomer));

    }


    private Accounts createNewAccount(Customer customer) {
        Accounts newAccount = new Accounts();
        newAccount.setCustomerId(customer.getCustomerId());
        long randomAccNumber = 1000000000L + new Random().nextInt();
        newAccount.setAccountNumber(randomAccNumber);

        newAccount.setAccountType(AccountsConstants.SAVINGS);
        newAccount.setBranchAddress(AccountsConstants.ADDRESS);
        return newAccount;
    }


    @Override
    public CustomerDTO fetchAccount(String mobileNumber) {
        Customer customer = customerRepository.findByMobileNumber(mobileNumber).orElseThrow(() ->
                new ResourceNotFoundException("Customer", "Mobile Number", mobileNumber));

        Accounts account = accountRepository.findByCustomerId(customer.getCustomerId()).orElseThrow(() ->
                new ResourceNotFoundException("Account", "Customer ID", customer.getCustomerId().toString()));

        CustomerDTO customerDTO = CustomerMapper.MapToCustomerDTO(customer, new CustomerDTO());
        customerDTO.setAccountsDTO(AccountsMapper.MapToAccountsDTO(account, new AccountsDTO()));
        return customerDTO;
    }

    @Override
    @Transactional
    public boolean updateAccount(CustomerDTO customerDTO) {
        boolean isUpdated = false;
        AccountsDTO accountsDTO = customerDTO.getAccountsDTO();
        if (accountsDTO != null) {
            Accounts accounts = accountRepository.findById(accountsDTO.getAccountNumber()).orElseThrow(() ->
                    new ResourceNotFoundException("Account", "Account Number", accountsDTO.getAccountNumber().toString()));

            AccountsMapper.MapToAccounts(accountsDTO, accounts);
            accounts = accountRepository.save(accounts);

            Long customerId = accounts.getCustomerId();
            Customer customer = customerRepository.findById(customerId).orElseThrow(() ->
                    new ResourceNotFoundException("Customer", "Customer ID", customerId.toString()));

            CustomerMapper.MapToCustomer(customerDTO, customer);
            customerRepository.save(customer);
            isUpdated = true;

        }
        return isUpdated;

    }

    @Override
    public boolean deleteAccount(String mobileNumber) {
        boolean isDeleted = false;
        Customer customer = customerRepository.findByMobileNumber(mobileNumber).orElseThrow(() ->
                new ResourceNotFoundException("Customer", "Mobile Number", mobileNumber));

        accountRepository.deleteByCustomerId(customer.getCustomerId());
        customerRepository.deleteById(customer.getCustomerId());
        isDeleted = true;
        return isDeleted;
    }
}
